// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjET_j-Nf1esXdr4qpmSzDYiWEebV5VRc',
    appId: '1:527870826105:web:81f26b20e868c17bb726a8',
    messagingSenderId: '527870826105',
    projectId: 'ecommerce-5be79',
    authDomain: 'ecommerce-5be79.firebaseapp.com',
    storageBucket: 'ecommerce-5be79.firebasestorage.app',
    measurementId: 'G-31G1QFZW8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdKOeH_dR1nzVGPub5TB8Zm6wM7ffo-nY',
    appId: '1:527870826105:android:1d77770f47e7413ab726a8',
    messagingSenderId: '527870826105',
    projectId: 'ecommerce-5be79',
    storageBucket: 'ecommerce-5be79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhnl7VToMylJms1D5WFXLLkP4qlX2yeWQ',
    appId: '1:527870826105:ios:dcec05c5dd33e060b726a8',
    messagingSenderId: '527870826105',
    projectId: 'ecommerce-5be79',
    storageBucket: 'ecommerce-5be79.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceCource',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhnl7VToMylJms1D5WFXLLkP4qlX2yeWQ',
    appId: '1:527870826105:ios:dcec05c5dd33e060b726a8',
    messagingSenderId: '527870826105',
    projectId: 'ecommerce-5be79',
    storageBucket: 'ecommerce-5be79.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceCource',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjET_j-Nf1esXdr4qpmSzDYiWEebV5VRc',
    appId: '1:527870826105:web:06cb6f22155be5ebb726a8',
    messagingSenderId: '527870826105',
    projectId: 'ecommerce-5be79',
    authDomain: 'ecommerce-5be79.firebaseapp.com',
    storageBucket: 'ecommerce-5be79.firebasestorage.app',
    measurementId: 'G-KEJ025D6GM',
  );
}
